name: tp2t
on:
  push:
    branches:
      - tp2
    tags:
      - v1

jobs:
  job_1:
    name: job principale
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
     name: Checkout 
     with:
	branch: tp2
    - name: Create artifact files
      run: |
        touch execution.md
    - name: execution  
      run: |
        make tp2s
        cat data/indices.txt | ./tp2s > execution.md

# Upload a single file artifact
    - name: 'Upload artifact'
      uses: ./
      with:
        name: 'Execution'
        path: execution.md
